### PR TITLE
fixes github.token

### PR DESCRIPTION
**Pull request by platinummonkey**
fixes github-token parsing error by github actions.

### CODE REVIEW

**Review by ntsd — APPROVED** [review]

**Comment by jillesme** [comment]
Could this be merged?

**Comment by kirudenk** [comment]
@ntsd, @platinummonkey, can this be merge, please?

**Comment by platinummonkey** [comment]
> @ntsd, @platinummonkey, can this be merge, please?

I don't have permissions to merge 😄

**Comment by ntsd** [comment]
> > @ntsd, @platinummonkey, can this be merge, please?
> 
> I don't have permissions to merge 😄

I thought you can merge after I approved. :)

**Pull request merged**
